apiVersion: v1
kind: Service
metadata:
  name: app-friends-quotes-service
spec:
  type: NodePort
  ports:
  - port: 4222
    targetPort: 4222
  selector:
    app: app-friends-quotes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-deployment
  annotations:
    pod.beta.kubernetes.io/hostname: nats-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-friends-quotes
  template:
    metadata:
      labels:
        app: app-friends-quotes
    spec:
      containers:
      - name: nats
        image: nats:latest
        ports:
          - containerPort: 4222
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: app-friends-quotes-pub-deployment
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: friends-quote-nats-pub
            image: cao89/friends-quote-nats-pub:beta4
          restartPolicy: OnFailure
