# Mostly from https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/application/mysql/mysql-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: nats_sub
        - name: MYSQL_USER
          value: nats_sub_user
        - name: MYSQL_PASSWORD
          value: nats_sub
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysql-initdb
        configMap:
          name: mysql-migrations
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-migrations
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS nats_sub;
    CREATE TABLE IF NOT EXISTS nats_sub.quotes (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, quote_str VARCHAR(300), friends_character VARCHAR(50), post_time DATETIME, ip VARCHAR(30), nats_subject VARCHAR(250));
